(()=>{const D=window.SOLANA_DATA;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const claims=new Map(D.claims.map(x=>[x.id,x]));const sources=new Map(D.sources.map(x=>[x.id,x]));const nodes=new Map(D.nodes.map(x=>[x.id,x]));const colors=['#66f5c4','#ae78ff','#f1c97b','#66c8ff','#ff8ebd','#a5ef72'];let view='nodes';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setView(next){view=next==='home'?'nodes':next;$$('.view').forEach(x=>x.classList.toggle('active',x.id===view));$('#hero').hidden=next!=='home';$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#nav').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');window.scrollTo({top:next==='home'?0:96,behavior:'smooth'});if(view==='graph')requestAnimationFrame(()=>drawGraph($('#graphFocus').value));}
$$('[data-view]').forEach(x=>x.addEventListener('click',()=>setView(x.dataset.view)));$('#menu').onclick=()=>{const open=$('#nav').classList.toggle('open');$('#menu').setAttribute('aria-expanded',open)};
$('#metrics').innerHTML=[['105','nodes'],['40','constellations'],['72','typed edges'],['52','Mapshifts']].map(([a,b])=>`<div><dt>${a}</dt><dd>${b}</dd></div>`).join('');
const unique=k=>[...new Set(D.nodes.map(n=>k(n)))].sort();for(const c of unique(n=>n.extensions.constellation))$('#constellation').insertAdjacentHTML('beforeend',`<option>${esc(c)}</option>`);for(const k of unique(n=>n.kind))$('#kind').insertAdjacentHTML('beforeend',`<option>${esc(k)}</option>`);for(const s of unique(n=>n.extensions.operational_status))$('#status').insertAdjacentHTML('beforeend',`<option>${esc(s)}</option>`);
function renderNodes(){const q=$('#search').value.toLowerCase(),c=$('#constellation').value,k=$('#kind').value,s=$('#status').value,o=$('#obscurity').value;const out=D.nodes.filter(n=>(!q||[n.label,n.summary,n.mechanism,n.extensions.constellation].join(' ').toLowerCase().includes(q))&&(!c||n.extensions.constellation===c)&&(!k||n.kind===k)&&(!s||n.extensions.operational_status===s)&&(!o||(o==='0'?n.extensions.obscurity<=1:o==='2'?n.extensions.obscurity>=2&&n.extensions.obscurity<=3:n.extensions.obscurity>=4)));$('#resultCount').textContent=`${out.length} of ${D.nodes.length} nodes`;$('#nodeGrid').innerHTML=out.map(n=>`<button class="node-card" data-node="${esc(n.id)}"><img loading="lazy" src="${n.asset}" alt=""><span class="body"><span class="eyebrow">${esc(n.extensions.constellation)}</span><h3>${esc(n.label)}</h3><p>${esc(n.summary)}</p><span class="tags"><span class="tag status">${esc(n.extensions.operational_status)}</span><span class="tag">${esc(n.kind)}</span><span class="tag">obscurity ${n.extensions.obscurity}</span></span></span></button>`).join('');$$('[data-node]').forEach(x=>x.onclick=()=>openNode(x.dataset.node));}
['search','constellation','kind','status','obscurity'].forEach(id=>$('#'+id).addEventListener('input',renderNodes));$('#clear').onclick=()=>{$('#search').value='';$('#constellation').value='';$('#kind').value='';$('#status').value='';$('#obscurity').value='';renderNodes()};
function openNode(id){const n=nodes.get(id),cl=claims.get(n.claim_refs[0]);const src=(cl?.evidence_refs||[]).map(id=>sources.get(id)).filter(Boolean);const incident=D.edges.filter(e=>e.source===id||e.target===id).slice(0,12);$('#nodeDetail').innerHTML=`<img src="${n.asset.replace('512','1024')}" alt=""><p class="eyebrow">${esc(n.extensions.constellation)}</p><h2>${esc(n.label)}</h2><div class="detail-meta"><span class="tag status">${esc(n.extensions.operational_status)}</span><span class="tag">${esc(n.kind)}</span><span class="tag">${esc(cl?.layer)}</span><span class="tag">confidence ${esc(cl?.confidence)}</span><span class="tag">as of ${esc(n.extensions.as_of)}</span></div><h3>Core record</h3><p>${esc(n.summary)}</p><h3>Functional chain</h3><p>${esc(n.mechanism)}</p><div class="directions"><article><b>Moving toward</b><h3>${esc(n.moving_toward.label)}</h3><p>${esc(n.moving_toward.description)}</p></article><article><b>Moving away</b><h3>${esc(n.moving_away.label)}</h3><p>${esc(n.moving_away.description)}</p></article></div><h3>Question</h3><p>${esc(n.question)}</p><h3>Practice</h3><p>${esc(n.practice)}</p><h3>Typed neighborhood</h3><ul>${incident.map(e=>`<li>${esc(nodes.get(e.source)?.label)} <b>${esc(e.predicate)}</b> ${esc(nodes.get(e.target)?.label)} — ${esc(e.mechanism)}</li>`).join('')||'<li>No release edge captured.</li>'}</ul><h3>Sources</h3><ul>${src.map(s=>`<li><a href="${esc(s.locator)}" target="_blank" rel="noreferrer">${esc(s.title)}</a> <span class="tag">${esc(s.kind)}</span></li>`).join('')}</ul>`;$('#nodeDialog').showModal();}
$('#nodeDialog .close').onclick=()=>$('#nodeDialog').close();$('#nodeDialog').addEventListener('click',e=>{if(e.target===$('#nodeDialog'))$('#nodeDialog').close()});
const focus=$('#graphFocus');focus.innerHTML='<option value="">Overview: 48-node sample</option>'+D.nodes.map(n=>`<option value="${n.id}">${esc(n.label)}</option>`).join('');focus.onchange=()=>drawGraph(focus.value);$('#graphReset').onclick=()=>{focus.value='';drawGraph('')};
function drawGraph(focusId){let subset;if(focusId){const edgeSet=D.edges.filter(e=>e.source===focusId||e.target===focusId);const ids=new Set([focusId,...edgeSet.flatMap(e=>[e.source,e.target])]);subset=D.nodes.filter(n=>ids.has(n.id));}else{subset=D.nodes.filter((_,i)=>i%2===0).slice(0,48)}const ids=new Set(subset.map(n=>n.id)),edges=D.edges.filter(e=>ids.has(e.source)&&ids.has(e.target));const W=1200,H=680,cx=W/2,cy=H/2;const groups=[...new Set(subset.map(n=>n.extensions.constellation))];const pos=new Map;subset.forEach((n,i)=>{const gi=groups.indexOf(n.extensions.constellation),base=gi/groups.length*Math.PI*2,local=i/subset.length*Math.PI*2;const r=focusId?210+(i%3)*62:130+(i%5)*78;pos.set(n.id,{x:cx+Math.cos(base+local*.35)*r,y:cy+Math.sin(base+local*.35)*r})});const line=edges.map(e=>{const a=pos.get(e.source),b=pos.get(e.target);return`<line class="${focusId?'hot':''}" x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}"><title>${esc(e.predicate)}: ${esc(e.mechanism)}</title></line>`}).join('');const g=subset.map((n,i)=>{const p=pos.get(n.id),col=colors[groups.indexOf(n.extensions.constellation)%colors.length];return`<g data-g-node="${n.id}" transform="translate(${p.x} ${p.y})"><circle r="${focusId&&n.id===focusId?18:10}" fill="${col}"><title>${esc(n.label)} · ${esc(n.extensions.constellation)}</title></circle><text x="15" y="4">${esc(n.label)}</text></g>`}).join('');$('#graphCanvas').innerHTML=`<svg viewBox="0 0 ${W} ${H}" aria-hidden="true">${line}${g}</svg>`;$$('[data-g-node]').forEach(x=>x.onclick=()=>{focus.value=x.dataset.gNode;drawGraph(x.dataset.gNode)});$('#graphLegend').innerHTML=groups.map((x,i)=>`<span style="border-color:${colors[i%colors.length]}">${esc(x)}</span>`).join('')}
const specialMaps=[
['Complete timeline','From the cryptographic-clock prehistory through the dated 2026 cutoff.','../timeline/solana-timeline.md'],
['Meme genealogy','BONK, WIF, pump.fun, graduation, social trading, extraction, community takeover, and afterlife.','../timeline/memecoin-history.md'],
['mtnDAO edition explorer','Ten dated Realm bindings plus the complete discoverable v9 project roster.','../mtndao/editions.md'],
['Outage & restart chronology','Separate incidents, mechanisms, coordination, repair, and legitimacy effects.','../timeline/outage-chronology.md'],
['FTX dependency map','Capital and Serum entanglement into OpenBook, BONK, bankruptcy memory, and recovery.','../timeline/ftx-chronology.md'],
['NFT migration map','Collections as portable nations, marketplace power, migration, return, and afterlife.','../timeline/nft-history.md'],
['Institutional-power map','Legal, technical, economic, social, distribution, and agenda-setting authority.','../constellations/foundation-labs-anza-and-institutional-power.md'],
['Validator & RPC topology','Hardware, stake, clients, QoS, access providers, restarts, and multi-client risk.','../constellations/validators-clients-and-network-operations.md'],
['Capital & liquidity flows','Patronage, DEX routing, leverage, collateral, stablecoins, and institutional settlement.','../constellations/dexs-and-liquidity.md'],
['Launchpad lifecycle','Issuance, bonding curve, graduation, routing, discovery, moderation, and social risk.','../constellations/pump-fun-and-launchpads.md'],
['Competitor matrix','Mechanism-level mirrors across execution, distribution, products, and ideology.','../constellations/competitors-and-alternatives.md'],
['AI-agent map','Human intent, identity, permission, payment, action, receipt, review, and remedy.','../constellations/ai-agents-and-agentic-commerce.md'],
['Consensus Reality map','Feeds, antagonists, memes, bots, tokenized belief, material consequence, and inspectable repair.','../constellations/crypto-twitter-and-consensus-reality.md']];
$('#specialMapGrid').innerHTML=specialMaps.map((x,i)=>`<a class="instrument map-link" href="${x[2]}"><span class="num">MAP ${String(i+1).padStart(2,'0')}</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p><b>Open source view →</b></a>`).join('');
$('#loopGrid').innerHTML=D.loops.map((x,i)=>`<article class="instrument"><span class="num">LOOP ${String(i+1).padStart(2,'0')}</span><h3>${esc(x.name.replace('-',' '))}</h3><p>${esc(x.sequence)}</p></article>`).join('');
$('#polarityGrid').innerHTML=D.polarities.map(x=>`<article><b>${esc(x.pole_a)}</b><span>↔</span><b>${esc(x.pole_b)}</b></article>`).join('');
$('#forceGrid').innerHTML=D.forces.map(x=>`<span title="${esc(x.threshold_policy)}">${esc(x.label)}</span>`).join('');
$('#mtnTimeline').innerHTML=D.realms.map((r,i)=>`<article class="realm ${i===9?'current':''}"><b>${esc(r.title)}</b><span>${esc(r.context.start)}–${esc(r.context.end)}</span><span>${esc(r.context.status_note)}</span></article>`).join('');$('#mtnProjects').innerHTML=D.mtnProjects.map(x=>`<span>${esc(x.project)}</span>`).join('');$('#mtnActivities').innerHTML=D.mtnActivities.map(x=>`<span>${esc(x.activity)}</span>`).join('');
const shifts=D.expressions.filter(x=>x.id.includes(':mapshift-'));let shiftIndex=0;function drawShift(i){shiftIndex=(i+shifts.length)%shifts.length;const e=shifts[shiftIndex],c=e.content;$('#mapshiftStage').innerHTML=`<article class="map-pane"><span class="label">Before map</span><h3>${esc(c.before_map)}</h3></article><div class="map-arrow">→</div><article class="map-pane after"><span class="label">After map</span><h3>${esc(c.after_map)}</h3><p class="practice"><b>Practice:</b> ${esc(c.practice)}</p></article>`}$('#randomShift').onclick=()=>drawShift(Math.floor(Math.random()*shifts.length));$('#mapshiftList').innerHTML=shifts.map((x,i)=>`<button data-shift="${i}">${esc(x.content.after_map)}</button>`).join('');$$('[data-shift]').forEach(x=>x.onclick=()=>{drawShift(+x.dataset.shift);$('#mapshiftStage').scrollIntoView({behavior:'smooth',block:'center'})});drawShift(0);
const spreads=D.expressions.filter(x=>x.kind==='spread');$('#readingGrid').innerHTML=spreads.map((x,i)=>`<article class="instrument"><span class="num">${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><p>${esc(x.content.instructions)}</p><ol>${x.content.positions.map(p=>`<li><b>${esc(p.role)}</b> — ${esc(p.question)}</li>`).join('')}</ol></article>`).join('');
const games=D.expressions.filter(x=>x.kind==='game');$('#gameGrid').innerHTML=games.map((x,i)=>`<article class="instrument"><span class="num">GAME ${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><p><b>${esc(x.content.semantic_kernel)}</b></p><p>${esc(x.content.rules)}</p><div class="tags"><span class="tag">${esc(x.content.players)}</span><span class="tag">${esc(x.content.duration)}</span></div></article>`).join('');
const lessons=D.expressions.filter(x=>x.kind==='lesson');$('#lessonGrid').innerHTML=lessons.map((x,i)=>`<article class="lesson"><span class="code">${String(i+1).padStart(2,'0')}</span><h3>${esc(x.title)}</h3><p>${esc(x.content.objective)}</p></article>`).join('');
function renderSources(){const q=$('#sourceSearch').value.toLowerCase();$('#sourceList').innerHTML=D.sources.filter(s=>!q||[s.title,s.kind,s.locator,s.rights_status].join(' ').toLowerCase().includes(q)).map(s=>`<article class="source"><a href="${esc(s.locator)}" target="_blank" rel="noreferrer">${esc(s.title)}</a><span>${esc(s.kind)}</span><span class="role">${esc(s.rights_status.split(';')[1]||s.rights_status)}</span></article>`).join('')}$('#sourceSearch').oninput=renderSources;renderSources();renderNodes();drawGraph('');$('#hero').hidden=false;})();
